In [1]:
import pandas as pd

df_air_reserve = pd.read_csv("/Users/aa370031/Dropbox/学习资料/数据分析/kaggle/Recruit Restaurant Visitor Forecasting/air_reserve.csv",low_memory=False)
df_air_store_info = pd.read_csv("/Users/aa370031/Dropbox/学习资料/数据分析/kaggle/Recruit Restaurant Visitor Forecasting/air_store_info.csv", low_memory=False)
df_air_visit_data = pd.read_csv("/Users/aa370031/Dropbox/学习资料/数据分析/kaggle/Recruit Restaurant Visitor Forecasting/air_visit_data.csv", low_memory=False)
df_date_info = pd.read_csv("/Users/aa370031/Dropbox/学习资料/数据分析/kaggle/Recruit Restaurant Visitor Forecasting/date_info.csv", low_memory=False)
df_hpg_reserve = pd.read_csv("/Users/aa370031/Dropbox/学习资料/数据分析/kaggle/Recruit Restaurant Visitor Forecasting/hpg_reserve.csv", low_memory=False)
df_hpg_store_info = pd.read_csv("/Users/aa370031/Dropbox/学习资料/数据分析/kaggle/Recruit Restaurant Visitor Forecasting/hpg_store_info.csv", low_memory=False)
df_store_id_relation = pd.read_csv("/Users/aa370031/Dropbox/学习资料/数据分析/kaggle/Recruit Restaurant Visitor Forecasting/store_id_relation.csv", low_memory=False)
df_sample_submission = pd.read_csv("/Users/aa370031/Dropbox/学习资料/数据分析/kaggle/Recruit Restaurant Visitor Forecasting/sample_submission.csv", low_memory=False)

In [10]:
df_air_reserve['visit_time'] = df_air_reserve.visit_datetime
df_air_reserve['reserve_time'] = df_air_reserve.reserve_datetime

def get_date(datetime):
    return datetime.split(' ')[0]

def get_time(datetime):
    return datetime.split(' ')[1]

df_air_reserve.visit_time = df_air_reserve.visit_time.apply(lambda x: get_time(x))
df_air_reserve.reserve_time = df_air_reserve.reserve_time.apply(lambda y: get_time(y))

df_air_reserve.visit_datetime = df_air_reserve.visit_datetime.apply(lambda x: get_date(x))
df_air_reserve.reserve_datetime = df_air_reserve.reserve_datetime.apply(lambda y: get_date(y))

IndexError: list index out of range

In [16]:
df_air_reserve.rename(columns={'visit_datetime': 'visit_date',
                               'reserve_datetime': 'reserve_date'}, inplace=True)

In [24]:
df = pd.merge(df_air_reserve, df_air_visit_data, how='left', on=['air_store_id', 'visit_date'])

In [29]:
pd.set_option('max_row', 200)
df.groupby(['air_store_id', 'visit_date']).sum()

                                 reserve_visitors  visitors
air_store_id         visit_date
air_00a91d42b08b08d9 2016-10-31                 2      26.0
                     2016-12-05                 9      33.0
                     2016-12-14                18      30.0
                     2016-12-17                 2      17.0
                     2016-12-20                 4      37.0
                     2017-02-18                 9      18.0
                     2017-02-23                12      40.0
                     2017-03-01                 3      17.0
                     2017-03-14                 4      28.0
                     2017-03-21                 3      28.0
                     2017-03-24                 2      34.0
                     2017-04-04                 2      17.0
air_0164b9927d20bcc3 2016-10-28                12      50.0
                     2016-11-01                10      34.0
                     2016-11-02                 3      10.0
                     2016-11-08                 9       9.0
                     2016-11-10                 6      14.0
                     2016-11-11                 4       6.0
                     2016-11-14                17      57.0
                     2016-11-15                 3       7.0
                     2016-11-16                 2       8.0
                     2016-11-18                13      36.0
                     2016-11-21                 3       3.0
                     2016-11-22                 9      20.0
                     2016-11-24                 2       2.0
                     2016-11-26                10      11.0
                     2016-11-28                 2       6.0
                     2016-12-02                 3      25.0
                     2016-12-05                 4      12.0
                     2016-12-06                 2       3.0
                     2016-12-07                 2       6.0
                     2016-12-08                 9      36.0
                     2016-12-14                 2       7.0
                     2016-12-15                15      69.0
                     2016-12-16                 6      36.0
                     2016-12-19                 2       2.0
                     2016-12-21                 2       7.0
                     2016-12-22                 7      36.0
                     2016-12-23                 2      10.0
                     2016-12-26                 2       3.0
                     2016-12-27                 3       7.0
                     2017-01-06                 3       5.0
                     2017-01-12                10      24.0
                     2017-01-13                 2      10.0
                     2017-01-14                 9      25.0
                     2017-01-16                 6      18.0
                     2017-01-17                 6      16.0
                     2017-01-19                 2       2.0
                     2017-01-20                 2       4.0
                     2017-01-23                11     114.0
                     2017-01-24                 5      12.0
                     2017-01-25                 2      10.0
                     2017-01-26                16      51.0
                     2017-01-27                 1      13.0
                     2017-01-31                13      54.0
                     2017-02-01                 8      48.0
                     2017-02-06                 4       5.0
                     2017-02-07                10      16.0
                     2017-02-08                 5       8.0
                     2017-02-09                13      48.0
                     2017-02-10                 5      28.0
                     2017-02-15                 2       2.0
                     2017-02-18                 9      22.0
                     2017-02-20                 1       2.0
                     2017-02-21                 6      30.0
                     2017-02-24                 4      11.0
                     2017-02-27                 2       4.0
                     2017-02-28                 2       3.0
                     2017-03-01                 4      48.0
                     2017-03-02                 6      48.0
                     2017-03-03                 3      12.0
                     2017-03-06                 4       8.0
                     2017-03-07                 3       5.0
                     2017-03-08                 6      21.0
                     2017-03-10                 6      12.0
                     2017-03-13                11      36.0
                     2017-03-14                 6      42.0
                     2017-03-17                 9      45.0
                     2017-03-22                11      54.0
                     2017-03-24                14      90.0
                     2017-03-27                 8      11.0
                     2017-03-28                 2      11.0
                     2017-03-29                 4      12.0
                     2017-03-30                 8      28.0
                     2017-03-31                 4       4.0
                     2017-04-03                 8      13.0
                     2017-04-05                10      60.0
                     2017-04-12                 1       2.0
                     2017-04-13                 9      26.0
                     2017-04-21                26      78.0
                     2017-04-25                 3       NaN
                     2017-04-26                 2       NaN
                     2017-04-27                 4       NaN
                     2017-05-01                 3       NaN
                     2017-05-02                 2       NaN
                     2017-05-05                 2       NaN
                     2017-05-09                 3       NaN
                     2017-05-13                10       NaN
air_034a3d5b40d5b1b1 2016-10-29                 3      19.0
                     2016-11-02                 2      10.0
...                                           ...       ...
air_fe22ef5a9cbef123 2017-04-15                 3      21.0
                     2017-04-21                 3      26.0
                     2017-04-22                 8      44.0
                     2017-04-29                 4       NaN
                     2017-04-30                 4       NaN
                     2017-05-04                 2       NaN
                     2017-05-05                10       NaN
                     2017-05-07                 2       NaN
air_fea5dc9594450608 2016-10-27                 4      20.0
                     2016-10-28                15      46.0
                     2016-11-01                 2       7.0
                     2016-11-02                 6      30.0
                     2016-11-05                 2      23.0
                     2016-11-09                 2       8.0
                     2016-11-11                 4      12.0
                     2016-11-12                 4      56.0
                     2016-11-16                 8      23.0
                     2016-11-17                 2       3.0
                     2016-11-18                 2      14.0
                     2016-11-19                 4      48.0
                     2016-11-22                 4      32.0
                     2016-11-24                 5      18.0
                     2016-11-25                 2       9.0
                     2016-11-26                 6      36.0
                     2016-11-29                 9      15.0
                     2016-11-30                15      27.0
                     2016-12-02                 8      14.0
                     2016-12-03                13      54.0
                     2016-12-07                13      36.0
                     2016-12-09                13      63.0
                     2016-12-10                 4      34.0
                     2016-12-12                 3       5.0
                     2016-12-17                13     132.0
                     2016-12-19                 2      16.0
                     2016-12-20                11      87.0
                     2016-12-24                 4      50.0
                     2016-12-25                 3      16.0
                     2016-12-26                 6      10.0
                     2016-12-27                 2      24.0
                     2016-12-28                 7      74.0
                     2017-01-10                 2      11.0
                     2017-01-12                 2      22.0
                     2017-01-13                 9      23.0
                     2017-01-14                 4      34.0
                     2017-01-16                 2       4.0
                     2017-01-17                 3      24.0
                     2017-01-18                 2      21.0
                     2017-01-19                 3      16.0
                     2017-01-20                 8      44.0
                     2017-01-21                 6      38.0
                     2017-01-26                13      54.0
                     2017-01-27                 4       9.0
                     2017-01-30                 2      15.0
                     2017-01-31                 2      10.0
                     2017-02-02                 4      84.0
                     2017-02-03                 9      27.0
                     2017-02-04                 2      31.0
                     2017-02-08                12      40.0
                     2017-02-10                 5       8.0
                     2017-02-11                 6      72.0
                     2017-02-13                 3      10.0
                     2017-02-16                 2      12.0
                     2017-02-17                 6      44.0
                     2017-02-18                 5      70.0
                     2017-02-20                10      20.0
                     2017-02-25                 4      52.0
                     2017-02-28                 2      18.0
                     2017-03-01                 8     111.0
                     2017-03-03                 6      78.0
                     2017-03-04                 3      15.0
                     2017-03-08                 2      15.0
                     2017-03-10                 3      17.0
                     2017-03-11                 7      75.0
                     2017-03-16                 3       7.0
                     2017-03-17                11      84.0
                     2017-03-18                10      46.0
                     2017-03-21                 5      16.0
                     2017-03-22                 2      21.0
                     2017-03-23                 8      22.0
                     2017-03-24                 2       6.0
                     2017-03-25                 6      39.0
                     2017-03-29                 2      14.0
                     2017-03-30                 5       6.0
                     2017-04-01                 2      33.0
                     2017-04-05                 4      16.0
                     2017-04-07                 2      23.0
                     2017-04-08                 5      31.0
                     2017-04-11                 4      15.0
                     2017-04-12                 2      15.0
                     2017-04-14                 2      20.0
                     2017-04-15                 4      40.0
                     2017-04-18                 2      16.0
                     2017-04-19                 2      17.0
                     2017-04-20                 6      23.0
                     2017-04-21                10      84.0
                     2017-04-22                 2      14.0
                     2017-04-25                 2       NaN
                     2017-04-28                 3       NaN
                     2017-05-20                 6       NaN
air_fee8dcf4d619598e 2017-01-09                 5      34.0

[29830 rows x 2 columns]